/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../..';
import name_ from './name';

const person: PersonDefinition = {
  name: name_,
};

export default person;
