/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import city_name from './city_name';
import postcode from './postcode';
import state from './state';

const location: LocationDefinition = {
  city_name,
  postcode,
  state,
};

export default location;
